name: Bug Report yml
description: File a bug with yml 
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: What went wrong?
    validations:
      required: true
  - type: dropdown
    id: labels
    attributes:
      label: Type
      options: [bug, enhancement]